module.exports = error_code = {
    //DOC
    DOC_MISSING_STATUS_CODE: 'DOC_INVALID_STATUS_CODE',
    DOC_MISSING_RESP_SCHEMA: 'DOC_MISSING_RESP_SCHEMA',
    DOC_MISS_MATCH_RESP_SCHEMA: 'DOC_MISS_MATCH_RESP_SCHEMA',
    DOC_MISS_MATCH_RESP_JSON: 'DOC_MISS_MATCH_RESP_JSON',

    //REQ
    API_REQ_INVALID_PATH: 'API_REQ_INVALID_PATH',
    API_REQ_PATH_NOT_DOC: 'API_REQ_PATH_NOT_DOC',
    API_REQ_MISSING_TOKEN: 'API_REQ_MISSING_TOKEN',

    //RES
    API_RES_LOC_HEADER_MISSING: 'API_RES_LOC_HEADER_MISSING',
    API_RES_CODE_NOT_DOC: 'API_RES_CODE_NOT_DOC',
    API_RES_CONTENT_TYPE_NOT_DOC: 'API_RES_CONTENT_TYPE_NOT_DOC',
    API_RES_JSON_MISS_MATCH_DOC: 'API_RES_JSON_MISS_MATCH_DOC',
    
};
